use phf::phf_map;
use std::fmt;

/// 惰性日志格式化字符串，仅在 Display::fmt 时才执行字符串替换
pub struct LogFmt {
    template: &'static str,
    args: Vec<(&'static str, String)>,
}

impl LogFmt {
    pub fn new(template: &'static str) -> Self {
        Self {
            template,
            args: Vec::new(),
        }
    }

    pub fn with_arg(mut self, key: &'static str, value: String) -> Self {
        self.args.push((key, value));
        self
    }
}

impl fmt::Display for LogFmt {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut s = self.template.to_string();
        for (key, value) in &self.args {
            let placeholder = format!("{{{}}}", key);
            s = s.replace(&placeholder, value);
        }
        write!(f, "{}", s)
    }
}

/// 用户可见文本
pub static USER_STRINGS: phf::Map<&'static str, &'static str> = phf_map! {
    // ── 错误信息 ──
    "error.not_found" => "[CQ:at,qq={qq}] 未找到该用户",
    "error.not_found_named" => "[CQ:at,qq={qq}] 找不到用户 \"{name}\"",
    "error.api_key" => "[CQ:at,qq={qq}] API Key 未配置",
    "error.oauth" => "[CQ:at,qq={qq}] OAuth 认证失败",
    "error.rate_limit" => "[CQ:at,qq={qq}] 请求过于频繁，请 {secs} 秒后再试",
    "error.rate_limit_generic" => "[CQ:at,qq={qq}] 请求过于频繁，请稍后再试",
    "error.client_rate_limit" => "[CQ:at,qq={qq}] 本地请求限流，请稍后再试",
    "error.query_failed" => "[CQ:at,qq={qq}] 查询失败，请稍后重试",
    "error.data_fetch_failed" => "[CQ:at,qq={qq}] 获取数据失败，请稍后再试",
    "error.db_error" => "[CQ:at,qq={qq}] 数据库错误",
    "error.image_send_failed" => "[CQ:at,qq={qq}] 图片发送失败",
    "error.audio_send_failed" => "[CQ:at,qq={qq}] 音频发送失败",
    "error.get_group_member_failed" => "[CQ:at,qq={qq}] 无法获取群成员列表，请稍后重试",
    "error.render_timeout" => "[CQ:at,qq={qq}] 渲染超时，请稍后重试",
    "error.render_failed" => "[CQ:at,qq={qq}] 渲染失败，请稍后重试",
    "error.beatmap_preview_convert_unsupported" => "[CQ:at,qq={qq}] 非 osu! 谱面不支持模式转换",
    "error.beatmap_preview_mods_invalid" => "[CQ:at,qq={qq}] !rv mod 互斥或不支持: {error}",
    "error.command_timeout" => "[CQ:at,qq={qq}] 命令处理超时，请稍后重试",
    "error.request_cancelled" => "请求已取消",
    "error.request_timeout" => "请求超时",
    "error.invalid_response" => "无效的响应数据",

    // ── 绑定相关 ──
    "bind.success" => "[CQ:at,qq={qq}] 成功绑定为{name}",
    "bind.already_bound" => "[CQ:at,qq={qq}] 你已经绑定为{name},如需修改请先解绑",
    "bind.pending_exists" => "[CQ:at,qq={qq}] 你已有进行中的绑定请求，请等待当前验证码过期后再试",
    "bind.code_sent" => "[CQ:at,qq={qq}] 您的验证码是 {code}，请在两分钟内通过osu!发送私信给 {target} 来完成验证",
    "bind.failed_retry" => "[CQ:at,qq={qq}] 绑定失败，请稍后重试",
    "bind.user_not_found" => "[CQ:at,qq={qq}] 未找到该 osu! 用户",
    "bind.already_bound_other" => "[CQ:at,qq={qq}] 该 osu! 用户已绑定其他QQ",
    "bind.wrong_person" => "[CQ:at,qq={qq}] 绑定失败（绑定的不是本人）",
    "bind.user_not_bound" => "[CQ:at,qq={qq}] 该用户还没有绑定 osu! 账号",
    "bind.not_bound" => "[CQ:at,qq={qq}] 你还没有绑定 osu! 账号，请使用 绑定 <用户名> 绑定",
    "bind.unbind_success" => "[CQ:at,qq={qq}] 解绑成功",
    "bind.unbind_failed" => "[CQ:at,qq={qq}] 解绑失败，请稍后重试",
    "bind.confirm_unbind" => "[CQ:at,qq={qq}] 确定要解除绑定 {name} 吗？回复\"解绑\"确认",
    "bind.not_bound_any" => "[CQ:at,qq={qq}] 你还没有绑定任何 osu! 用户",
    "bind.mentioned_not_bound" => "[CQ:at,qq={qq}] 该用户未绑定 osu! 账号，请使用 绑定 <osu用户名> 命令绑定",
    "bind.irc_already_bound_other" => "[CQ:at,qq={qq}] 绑定失败（该 osu! 用户已绑定其他 QQ）",
    "bind.irc_user_not_found" => "[CQ:at,qq={qq}] 绑定失败（用户不存在）",

    // ── 查询相关 ──
    "query.no_records" => "[CQ:at,qq={qq}] 最近没有游玩记录（包括失败）",
    "query.no_records_pass" => "[CQ:at,qq={qq}] 最近没有游玩记录",
    "query.no_match" => "[CQ:at,qq={qq}] 没有符合条件的{name}",
    "query.index_out_of_range" => "[CQ:at,qq={qq}] 没有第{pos}条{name}，只有{total}条",
    "query.no_score_on_map" => "[CQ:at,qq={qq}] 该玩家在此谱面上没有成绩",
    "query.score_not_found" => "[CQ:at,qq={qq}] 未找到该成绩",
    "query.score_fetch_failed" => "[CQ:at,qq={qq}] 获取成绩失败，请稍后再试",
    "query.user_info_failed" => "[CQ:at,qq={qq}] 无法获取该玩家信息",
    "query.need_beatmap_or_cache" => "[CQ:at,qq={qq}] 请提供谱面 ID 或先查询一张图",
    "query.no_bound_users" => "[CQ:at,qq={qq}] 你群根本没有人绑定 osu! 账号",
    "query.profile_not_bound" => "[CQ:at,qq={qq}] 请先绑定 osu! 用户名，或使用 !profile <用户名> 查询他人",
    "query.noun_replay" => "记录",
    "query.noun_score" => "成绩",
    "query.noun_best" => "最佳成绩",
    "query.noun_today_best" => "今日最佳",
    "query.no_records_best" => "[CQ:at,qq={qq}] 暂无最佳成绩",
    "query.no_records_today_best" => "[CQ:at,qq={qq}] 今天暂无打入最佳榜的成绩",

    // ── 格式化输出 ──
    "fmt.recent_pass" => "最近通过",
    "fmt.recent_play" => "最近游玩",
    "fmt.playtime_detail" => "{hours} 小时 {minutes} 分钟 {seconds} 秒",
    "fmt.score_list_header" => "{username}的{label} ({mode})：\n",
    "fmt.profile_header" => "的个人信息—",
    "fmt.profile_pp" => "pp 表现",
    "fmt.no_pp" => "--",
    "fmt.profile_ranked_score" => "m Ranked谱面总分",
    "fmt.profile_accuracy" => " 准确率",
    "fmt.profile_playcount" => " 游玩次数",
    "fmt.profile_hits" => " 总命中次数",
    "fmt.profile_playtime" => "游玩时间",
    "fmt.beatmap_score" => "谱面成绩",
    "fmt.best_score" => "最高成绩",
    "fmt.today_best" => "今日最佳",
    "fmt.score_count" => "{} 条记录",

    // ── 高光 ──
    "highlight.most_pp" => "最飞升：\n",
    "highlight.no_pp" => "你群没有人飞升。\n",
    "highlight.most_hits" => "最肝：\n",
    "highlight.no_hits" => "你群没有人肝。\n",
    "highlight.most_playtime" => "最长游戏时间：\n",
    "highlight.no_playtime" => "你群没有人玩。\n",
    "highlight.no_data" => "你群根本没有人屙屎。",
    "highlight.pp_increase" => "{username} 增加了 {pp} PP。\n({old} -> {new})\n",
    "highlight.hits_increase" => "{username} 打了 {hits} 下。\n",
    "highlight.playtime_increase" => "{username} 玩儿了 {hours} 小时。\n",

    // ── 模式配置 ──
    "mode.set_success" => "[CQ:at,qq={qq}] 已设置默认模式为 {mode}",
    "mode.get_success" => "[CQ:at,qq={qq}] 你的默认模式是 {mode}",
    "mode.not_bound" => "[CQ:at,qq={qq}] 你还没有绑定 osu! 账号，无法设置默认模式",

    // ── 比赛监听 (!ml) ──
    "ml.start_success" => "[CQ:at,qq={qq}] 已开始监听比赛 {match_id}（{match_name}）",
    "ml.stop_success" => "[CQ:at,qq={qq}] 已停止监听比赛 {match_id}",
    "ml.stop_all_success" => "[CQ:at,qq={qq}] 已停止监听本群所有比赛（{count} 个）",
    "ml.list_header" => "本群正在监听的比赛（{count} 个）：\n",
    "ml.list_empty" => "[CQ:at,qq={qq}] 本群当前没有监听任何比赛",
    "ml.list_item" => "#{idx} 比赛 {match_id}（{match_name}）— 由 {username} 发起，状态：{status}",
    "ml.not_found" => "[CQ:at,qq={qq}] 未找到比赛 {match_id}，或本群未监听该比赛",
    "ml.already_listening" => "[CQ:at,qq={qq}] 本群已在监听比赛 {match_id}",
    "ml.limit_exceeded" => "[CQ:at,qq={qq}] 监听数量已达上限（{limit} 个），请先停止其他比赛",
    "ml.status_header" => "比赛 {match_id} 状态：\n",
    "ml.status_name" => "名称：{name}\n",
    "ml.status_status" => "状态：{status}\n",
    "ml.status_players" => "参赛人数：{count}\n",
    "ml.status_games" => "已记录谱面：{count} 场\n",
    "ml.fetch_failed" => "[CQ:at,qq={qq}] 获取比赛信息失败，请稍后重试",
    "ml.match_ended" => "[CQ:at,qq={qq}] 比赛 {match_id} 已结束",
    "ml.new_game_notification" => "比赛 {match_name} 新场次开始：\n{game_info}",
    "ml.match_completed_notification" => "比赛 {match_name} 已结束！\n最终结果：\n{result_summary}",
    "ml.unknown" => "未知",
    "ml.unknown_player" => "未知玩家",
    "ml.listener_active_status" => "监听中",
    "ml.listener_stopped_status" => "已停止",
    "ml.match_status_finished" => "已结束",
    "ml.match_status_in_progress" => "进行中",
    "ml.fallback_finished_header" => "【{match_name}】场次结束",
    "ml.fallback_started_header" => "【{match_name}】场次开始",
    "ml.fallback_selected_beatmap" => "选图：Beatmap #{beatmap_id}",
    "ml.fallback_players_header" => "参加玩家：",
    "ml.fallback_no_players" => "- 暂无玩家信息",
    "ml.event_match_created" => "比赛创建",
    "ml.event_match_disbanded" => "比赛解散",
    "ml.event_player_joined" => "玩家加入",
    "ml.event_player_left" => "玩家离开",
    "ml.event_player_kicked" => "玩家被踢出",
    "ml.event_host_changed" => "房主变更",
    "ml.event_beatmap_changed" => "选图变更",
    "ml.event_match_started" => "比赛开始",
    "ml.event_match_completed" => "场次结束",
    "ml.event_generic" => "事件",

    // ── 系统 ──
    "sys.help" => "绑定/解绑/~/where/查@/今日高光/!p/!r/!s/!b/!ps/!rs/!ss/!bs/!t/!a/!profile/!mode/!rv/!ml/!help\n\n更多细节请移步 github.com/ZnCookie/osubot-rs/blob/master/docs/commands.md 查阅",

    // ── BridgeError 用户可见 ──
    "bridge.rate_limit_send_msg" => "消息发送过于频繁，请稍后再试",
    "bridge.rate_limit_http" => "请求过于频繁，请稍后再试",
    "bridge.tick_interval_too_short" => "tick 间隔不能小于 {secs} 秒",
    "bridge.tick_interval_too_long" => "tick 间隔不能大于 {secs} 秒",
    "bridge.tick_limit_exceeded" => "每个插件最多注册 {limit} 个 tick",

    // ── 配置校验 ──
    "config.ml_poll_interval_too_small" => "match_listen.poll_interval_secs 过小（{current} < 5 秒）",
};

/// 开发者可见文本（log 消息），统一中文
pub static LOG_STRINGS: phf::Map<&'static str, &'static str> = phf_map! {
    // ===== osubot/src/main.rs =====
    "main.persist_user_id_failed" => "无法持久化来自上游的 user_id: {error}",
    "main.persist_binding_failed" => "无法持久化来自上游的绑定: {error}",
    "main.update_binding_failed" => "无法更新绑定用户名",
    "main.cache_user_id_failed" => "无法缓存 user_id",
    "main.calculate_change_failed" => "无法计算变化",
    "main.log_label_success" => "{label} 成功",
    "main.log_label_failed" => "{label} 失败",
    "main.resolve_score_user_start" => "resolve_score_user: 开始",
    "main.resolve_score_user_lookup" => "resolve_score_user: 通过用户名 '{username}' 查找",
    "main.resolve_score_user_api_failed" => "resolve_score_user: API 查找失败",
    "main.resolve_score_user_fetch_stats" => "resolve_score_user: 获取 user_id={user_id} 的数据",
    "main.resolve_score_user_lookup_bound_failed" => "resolve_score_user: 已绑定用户的 API 查找失败",
    "main.handle_score_query_start" => "handle_score_query: 开始",
    "main.handle_score_query_bound" => "handle_score_query: 已绑定用户, user_id={user_id}, username={username}",
    "main.score_query_command" => "成绩查询命令",
    "main.score_query_failed" => "成绩查询失败",
    "main.score_query_error_details" => "成绩查询错误详情",
    "main.resolve_bound_user_failed" => "resolve: 已绑定用户的 API 查找失败",
    "main.resolve_score_user_resolved" => "resolve_score_user: 已解析 user_id={user_id}, username={username}",
    "main.resolve_score_user_none" => "resolve_score_user: 返回 None",
    "main.fetch_scores" => "获取 user_id={user_id}, mode={mode}, limit={limit} 的成绩",
    "main.score_list_card_rendered" => "成绩列表卡片已渲染, {bytes} 字节",
    "main.render_score_list_failed_text" => "render_score_list_card 失败，回退到文本",
    "main.render_score_list_timeout_text" => "render_score_list_card 超时，回退到文本",
    "main.score_by_id" => "通过 score_id 查询谱面成绩",
    "main.get_score_by_id_failed" => "get_score_by_id 失败",
    "main.fetch_stats_score_id_failed" => "fetch_user_stats_by_user_id 在 score_id 查询中失败",
    "main.score_on_beatmap" => "谱面成绩查询",
    "main.get_user_beatmap_scores_failed" => "get_user_beatmap_scores_all 失败",
    "main.respond_err_send_failed" => "respond_err 发送失败（响应通道已关闭）",
    "main.ur_calculation_start" => "开始 UR 计算",
    "main.ur_calculation_succeeded" => "UR 计算成功",
    "main.ur_calculation_none" => "UR 计算返回 None",
    "main.ur_calculation_timeout" => "UR 计算超时",
    "main.ur_calculation_skipped" => "跳过 UR 计算",
    "main.render_score_card_failed_text" => "render_score_card 失败，回退到文本",
    "main.render_score_card_timeout_text" => "render_score_card 超时，回退到文本",
    "main.command_disabled" => "命令已禁用，跳过",
    "main.query_self" => "QuerySelf 命令",
    "main.query_self_auto_bound" => "QuerySelf 通过上游自动绑定",
    "main.query_self_no_binding" => "QuerySelf 无绑定",
    "main.query_self_db_error" => "QuerySelf 数据库错误",
    "main.query_user" => "QueryUser 命令",
    "main.query_user_success" => "QueryUser 成功",
    "main.query_user_no_change" => "QueryUser - 无变化数据",
    "main.query_user_failed" => "QueryUser 失败",
    "main.query_mentioned_user" => "QueryMentionedUser 命令",
    "main.query_mentioned_auto_bound" => "QueryMentionedUser 通过上游自动绑定",
    "main.query_mentioned_no_binding" => "QueryMentionedUser 无绑定",
    "main.query_mentioned_db_error" => "QueryMentionedUser 数据库错误",
    "main.bind_command" => "Bind 命令",
    "main.bind_already_bound" => "Bind 但已绑定",
    "main.bind_check_pending_failed" => "检查待定绑定失败",
    "main.bind_pending_created" => "待定绑定已创建",
    "main.bind_create_pending_failed" => "创建待定绑定失败",
    "main.bind_success" => "绑定成功",
    "main.bind_failed_already_bound" => "绑定失败 - 用户名已绑定",
    "main.bind_failed" => "绑定失败",
    "main.bind_user_not_found" => "Bind 但未找到用户",
    "main.bind_user_info_failed" => "Bind - 用户信息检查失败",
    "main.bind_db_error" => "Bind 数据库错误",
    "main.unbind_command" => "Unbind 命令",
    "main.unbind_remove_pending_failed" => "无法移除待定解绑",
    "main.unbind_success" => "解绑成功",
    "main.unbind_failed" => "解绑失败",
    "main.unbind_set_pending_failed" => "无法设置待定解绑",
    "main.unbind_confirmation" => "已请求解绑确认",
    "main.unbind_no_binding" => "Unbind 无绑定",
    "main.unbind_db_error" => "Unbind 数据库错误",
    "main.unbind_pending_check_error" => "Unbind 待定检查错误",
    "main.highlight_command" => "Highlight 命令",
    "main.highlight_group_member_failed" => "无法获取群成员列表",
    "main.highlight_fetch_bindings_failed" => "Highlight 无法获取绑定",
    "main.highlight_fetch_failed" => "Highlight 获取失败",
    "main.profile_card_cached" => "ProfileCard 从本地缓存解析",
    "main.profile_card_by_username" => "ProfileCard 通过用户名解析",
    "main.profile_card_resolution_failed" => "ProfileCard 用户名解析失败",
    "main.profile_card_mention" => "ProfileCard 提及",
    "main.profile_card_mention_bound" => "ProfileCard 提及自动绑定",
    "main.profile_card_mention_no_binding" => "ProfileCard 提及无绑定",
    "main.profile_card_mention_db_error" => "ProfileCard 提及数据库错误",
    "main.profile_card_self" => "ProfileCard 自身",
    "main.profile_card_self_bound" => "ProfileCard 自身自动绑定",
    "main.profile_card_db_error" => "ProfileCard 数据库错误",
    "main.profile_card_command" => "ProfileCard 命令",
    "main.profile_card_html_fetched" => "ProfileCard HTML 已获取",
    "main.profile_card_render_timeout" => "ProfileCard 渲染超时",
    "main.profile_card_render_failed" => "渲染失败",
    "main.profile_card_rendered" => "ProfileCard 已渲染",
    "main.profile_card_failed" => "ProfileCard 失败",
    "main.score_on_beatmap_cmd" => "ScoreOnBeatmap 命令",
    "main.pass_command" => "Pass 命令",
    "main.recent_command" => "Recent 命令",
    "main.best_score_command" => "Best 命令",
    "main.today_best_command" => "TodayBest 命令",
    "main.help_command" => "Help 命令",
    "main.send_group_msg_failed" => "发送群消息失败: {error}",
    "main.send_image_failed" => "无法发送群图片消息",
    "main.send_record_failed" => "无法发送群语音消息",
    "main.irc_no_pending_bind" => "未找到匹配 IRC 验证码的待定绑定",
    "main.irc_pending_bind_db_error" => "查找待定绑定的数据库错误",
    "main.irc_pending_bind_username_mismatch" => "无法移除待定绑定（用户名不匹配）",
    "main.remove_pending_bind_failed" => "无法移除待定绑定: {error}",
    "main.irc_bind_verified" => "绑定已验证并完成",
    "main.irc_bind_user_not_found" => "用户 {username} 在 IRC 绑定时未找到",
    "main.irc_bind_fetch_failed" => "IRC 绑定时无法获取 {username} 的用户信息: {error}",
    "main.startup" => "正在启动 osubot...",
    "main.onebot_url" => "OneBot URL: {url}",
    "main.backfilling" => "正在回填 {count} 个用户的 user_id...",
    "main.backfilled" => "已缓存 {username} 的 user_id: {user_id}",
    "main.backfill_not_found" => "回填时未找到用户 {username}",
    "main.backfill_fetch_failed" => "回填时无法获取 {username} 的用户信息: {error}",
    "main.all_users_cached" => "所有已绑定用户已有缓存的 user_id",
    "main.backfill_query_failed" => "无法查询无 ID 的用户: {error}",
    "main.irc_client_error" => "IRC 客户端错误",
    "main.oauth_not_configured" => "osu! API v2 client_secret 未配置。请在 osubot.toml 中设置 osu.client_secret",
    "main.cleanup_stale_pending" => "已清理过期的待处理 OneBot API 条目",
    "main.file_watcher_exited" => "文件监控任务已退出，热重载功能不可用",
    "main.file_watcher_join_error" => "文件监控任务 JoinHandle 错误: {error}",
    "main.no_ws_dropping_irc" => "没有活动的 WebSocket 连接，丢弃 IRC 消息",
    "main.shutdown_signal" => "收到关闭信号，正在优雅关闭...",
    "main.shutdown_no_reconnect" => "正在关闭，不再重连",
    "main.shutdown_during_reconnect_sleep" => "收到关闭信号，中断重连等待",
    "main.shutdown_during_connect_sleep" => "收到关闭信号，中断连接等待",
    "main.connecting_ws" => "正在连接 OneBot WebSocket",
    "main.ws_connect_failed" => "WebSocket 连接失败，{secs}秒后重试",
    "main.ws_connected" => "WebSocket 连接已建立",
    "main.ws_sink_close_failed" => "无法关闭旧的 WebSocket sink",
    "main.ws_ping_failed" => "WebSocket ping 失败",
    "main.plugin_channel_closed" => "插件发送通道已关闭",
    "main.plugin_manager_init" => "插件管理器已初始化，共 {count} 个插件",
    "main.plugin_init_failed" => "插件初始化失败: {error}",
    "main.plugin_msg_channel_busy" => "plugin message channel busy: {error}",
    "main.force_reconnect_url_changed" => "强制重连：onebot_url 已热重载变更",
    "main.group_filtered" => "群被过滤，跳过",
    "main.hot_reload_skip" => "热重载中，跳过消息",
    "main.command_timeout" => "命令处理超时（{secs}秒）",
    "main.ws_closed_reconnect" => "WebSocket 连接关闭，{secs}秒后重连",
    "main.ws_error_reconnect" => "WebSocket 错误，{secs}秒后重连",
    "main.ws_stream_ended" => "WebSocket 流结束，{secs}秒后重连",
    "main.ws_message_rate_limited" => "WebSocket 消息速率超限（{limit} 条/秒），已丢弃",

    // ===== osubot/src/reload.rs =====
    "reload.coordinator_fatal" => "ReloadCoordinator 致命错误: {error}",
    "reload.file_watch_started" => "文件监控已启动: config={config}, plugins={plugins}",
    "reload.file_change_detected" => "收到文件变更，开始热重载...",
    "reload.config_reload_failed" => "配置重载失败，保留旧配置并跳过插件重载: {error}",
    "reload.drain_timeout" => "任务超时未排空，跳过插件重载以避免实例索引混乱",
    "reload.plugin_reload_failed_rollback" => "插件重载失败，回滚配置: {error}",
    "reload.plugin_dir_watch_updated" => "插件目录监控已更新: {old} → {new}",
    "reload.config_validated" => "配置验证通过，等待插件重载...",
    "reload.oauth_credentials_changed" => "osu! API 凭据已变更，正在更新 OAuth 缓存",
    "reload.irc_config_changed" => "IRC 配置已变更，正在重启连接",
    "reload.onebot_url_changed" => "onebot_url 已变更，触发重连",
    "reload.config_reload_success" => "配置热重载成功（含副作用应用）",
    "reload.plugin_manager_not_init" => "PluginManager 未初始化（可能在启动时未启用插件），已启用插件将在下次 OneBot 重连后加载",
    "reload.plugin_reload_success" => "插件热重载成功",
    "reload.drain_wait_timeout" => "等待进行中任务超时 ({timeout}s)，强制切换",
    "reload.irc_disabled" => "IRC 已禁用，连接已关闭",
    "reload.irc_skipped" => "IRC 已启用但 nickname/password 为空，跳过重连",
    "reload.irc_client_error" => "IRC 客户端错误",
    "reload.irc_restarted" => "IRC 连接已重启",
    "reload.unknown_upstream" => "未知的上游 provider 类型: {provider}",
    "reload.err_read_failed" => "读取配置文件失败: {error}",
    "reload.err_toml_parse" => "TOML 解析失败: {error}",
    "reload.unwatch_old_dir_failed" => "unwatch old plugin dir failed: {error}",
    "reload.watch_new_dir_failed" => "watch new plugin dir failed: {error}",

    // ===== osubot/src/scheduler.rs =====
    "scheduler.pruned_records" => "已清理旧记录",
    "scheduler.prune_records_failed" => "无法清理旧记录",
    "scheduler.pruned_pending_binds" => "已清理过期的待定绑定",
    "scheduler.prune_pending_binds_failed" => "无法清理过期的待定绑定",
    "scheduler.pruned_pending_unbinds" => "已清理过期的待定解绑",
    "scheduler.prune_pending_unbinds_failed" => "无法清理过期的待定解绑",
    "scheduler.task_started" => "调度任务已启动",
    "scheduler.shutting_down" => "调度器正在关闭",
    "scheduler.tick" => "调度器心跳",
    "scheduler.get_due_users_failed" => "get_due_users 失败: {error}",
    "scheduler.due_users_count" => "到期用户数: {count}",
    "scheduler.set_next_update_failed" => "为用户 {user_id}/{mode} 设置下次更新失败: {error}",
    "scheduler.username_change_detected" => "调度器检测到用户名变更",
    "scheduler.save_stats_error" => "保存 {user_id}/{mode} 数据时出错: {error}",
    "scheduler.get_snapshot_error" => "获取 {user_id}/{mode} 的快照时出错: {error}",
    "scheduler.fetch_recent_failed" => "获取用户 {user_id} 的最近游玩失败: {error}",
    "scheduler.save_records_failed" => "保存 {user_id}/{mode} 的游玩记录失败: {error}",
    "scheduler.set_last_update_failed" => "为用户 {user_id}/{mode} 设置上次更新失败: {error}",
    "scheduler.config_changed_reset" => "配置变更，已重置所有用户更新排程",
    "scheduler.reset_schedule_failed" => "重置排程失败: {error}",

    // ===== osubot/src/xfs_upstream.rs =====
    "xfs.build_request_failed" => "xfs: 构建 WS 请求失败: {error}",
    "xfs.invalid_self_id" => "xfs: 无效的 self_id 头",
    "xfs.invalid_access_token" => "xfs: 无效的 access_token 头",
    "xfs.invalid_client_role" => "xfs: 无效的 X-Client-Role 头",
    "xfs.connect_failed" => "xfs: WS 连接失败: {error}",
    "xfs.connect_timeout" => "xfs: WS 连接超时",
    "xfs.plan_request" => "计划请求",
    "xfs.actual_send" => "实际发送",
    "xfs.send_event_failed" => "xfs: 发送事件失败",
    "xfs.ws_read_error" => "xfs: WS 读取错误",
    "xfs.server_response" => "服务器返回",
    "xfs.resolved_username" => "xfs: 从上游解析了用户名",
    "xfs.skipping_api" => "xfs: 跳过 osu! API 解析 - 未配置凭据",
    "xfs.resolve_failed" => "xfs: 无法将用户名解析为 user_id",
    "xfs.parse_result" => "解析结果",
    "xfs.response_timeout" => "xfs: 等待响应超时",
    "xfs.relay_api_failed" => "NOTE: relay 已响应但 osu! API 解析失败（测试中无凭据）",

    // ===== osubot/src/yumu_upstream.rs =====
    "yumu.build_request_failed" => "yumu: 构建 WS 请求失败: {error}",
    "yumu.invalid_access_token" => "yumu: 无效的 access_token 头",
    "yumu.invalid_client_role" => "yumu: 无效的 X-Client-Role 头",
    "yumu.invalid_self_id" => "yumu: 无效的 X-Self-ID 头",
    "yumu.connect_failed" => "yumu: WS 连接失败: {error}",
    "yumu.connect_timeout" => "yumu: WS 连接超时",
    "yumu.send_lifecycle_failed" => "yumu: 发送生命周期事件失败",
    "yumu.send_event_failed" => "yumu: 发送事件失败",
    "yumu.ws_read_error" => "yumu: WS 读取错误",
    "yumu.received_message" => "接收到消息",
    "yumu.parsed_send_action" => "已解析发送操作",
    "yumu.parsed_binding" => "已解析绑定",
    "yumu.response_timeout" => "yumu: 等待响应超时",
    "yumu.no_binding_test" => "NOTE: 未找到 QQ 3628905173 的绑定（测试中符合预期）",
    "yumu.binding_found" => "找到绑定: {osu_id} {username}",

    // ===== osubot-core/src/ur.rs =====
    "ur.replay_cached" => "回放从缓存加载",
    "ur.replay_404" => "回放下载 404",
    "ur.replay_request_sent" => "回放下载请求已发送",
    "ur.replay_downloaded" => "回放下载成功",
    "ur.create_cache_dir_failed" => "无法创建回放缓存目录",
    "ur.write_cache_failed" => "无法写入回放缓存",
    "ur.replay_parsed" => "已解析带 lazer 时间修正的回放",
    "ur.key_times_extracted" => "已从回放中提取按键时间",
    "ur.match_hits_complete" => "match_hits 完成",
    "ur.skip_non_osu" => "跳过 UR/PP 计算：非 osu! 模式",
    "ur.downloading_replay" => "正在下载用于 UR/PP 计算的回放",
    "ur.replay_arrived" => "回放已下载",
    "ur.replay_download_failed" => "无法下载回放",
    "ur.beatmap_downloaded" => "谱面已下载",
    "ur.beatmap_download_failed" => "无法下载谱面",
    "ur.beatmap_parse_failed" => "无法解析谱面",
    "ur.no_hit_objects" => "谱面中无打击对象",
    "ur.parsed_beatmap_info" => "已解析谱面信息",
    "ur.parsed_replay_times" => "已解析回放按键时间",
    "ur.parse_replay_times_failed" => "无法解析回放按键时间",
    "ur.matched_hits" => "已匹配打击",
    "ur.calculated_timing_errors" => "已计算时间误差",
    "ur.first_timing_errors" => "前 5 个时间误差",
    "ur.timing_error_stats" => "时间误差统计",
    "ur.no_timing_errors" => "无时间误差，跳过 UR 计算",
    "ur.calculation_complete" => "UR 计算完成",
    "ur.calculation_panicked" => "UR/PP 计算 panic",

    // ===== osubot-core/src/api.rs =====
    "api.cache_dir_failed" => "无法创建缓存目录: {error}",
    "api.write_beatmap_cache_failed" => "无法写入谱面缓存文件 {path}: {error}",
    "api.parse_osu_failed" => "无法解析 .osu 文件",
    "api.try_mode_failed" => "try_mode 失败; 无法转换",
    "api.ifacc_parse_failed" => "无法解析用于 if-acc 的 .osu 文件",
    "api.pp_download_failed" => "无法下载用于 PP 计算的 .osu 文件",
    "api.pp_calc_panicked" => "PP 计算任务 panic",
    "api.mod_deserialize_failed" => "无法反序列化 mod，回退到基础 mod",
    "api.mod_settings_deserialize_failed" => "无法反序列化含设置的 mod，回退到基础 mod",
    "api.parse_user_from_score_failed" => "无法从成绩响应中解析用户",
    "api.deserialize_failed" => "API 响应反序列化失败",
    "api.rwlock_recovering" => "RwLock 被污染，正在恢复",
    "api.retry_after" => "在 Retry-After 头后重试",
    "api.retry_transient" => "重试临时 API 错误",
    "api.backfill_beatmapset_failed" => "无法回填谱面集元数据",
    "api.backfilled_score_value" => "从详情接口回填了成绩值",
    "api.score_detail_no_value" => "成绩详情接口未返回值",
    "api.backfill_score_failed" => "无法回填成绩值",
    "api.parse_score_json_failed" => "无法解析成绩 JSON",
    "api.beatmap_score_404_retry" => "谱面成绩 404，用 legacy_only=1 重试",
    "api.beatmap_score_retry_parse_failed" => "BeatmapScore 重试解析失败",
    "api.beatmap_score_parse_failed" => "BeatmapScore 解析失败",
    "api.beatmap_scores_404_retry" => "谱面成绩列表 404，用 legacy_only=1 重试",
    "api.beatmap_scores_retry_parse_failed" => "BeatmapScoresAll 重试解析失败",
    "api.beatmap_scores_parse_failed" => "BeatmapScoresAll 解析失败",
    "api.fetch_score_detail" => "正在获取成绩详情",
    "api.score_detail_404" => "成绩详情接口 404",
    "api.score_detail_response" => "成绩详情接口响应",

    // ===== osubot-core/src/irc.rs =====
    "irc.disabled" => "IRC 已禁用，跳过连接",
    "irc.connecting" => "正在连接 IRC",
    "irc.listener_exited" => "IRC 监听器正常退出，正在重连...",
    "irc.connection_error" => "IRC 连接错误，正在重连...",
    "irc.waiting_reconnect" => "等待重连",
    "irc.connected" => "IRC 连接已建立",
    "irc.closed_by_server" => "IRC 连接被服务器关闭",
    "irc.read_error" => "IRC 读取错误",
    "irc.read_timeout_reconnect" => "IRC 连续两次读取超时，正在重连",
    "irc.read_timeout_ping" => "IRC 读取超时，发送 PING 检查连接",
    "irc.ping_failed" => "PING 发送失败",
    "irc.pong_received" => "IRC PONG 已接收",
    "irc.non_privmsg" => "IRC 非 PRIVMSG 消息",
    "irc.privmsg_received" => "收到 IRC 私信",
    "irc.send_failed" => "无法向频道发送 IRC 消息",

    // ===== osubot-core/src/cache.rs =====
    "cache.cutoff_time_failed" => "无法计算 {name} 清理的截止时间",
    "cache.read_dir_failed" => "无法读取 {name} 目录进行清理: {error}",
    "cache.read_entry_failed" => "无法在清理时读取 {name} 目录条目: {error}",
    "cache.delete_failed" => "无法删除 {name} 文件 {path}: {error}",
    "cache.cleanup_summary" => "{name} 清理: 已删除 {deleted} 个, {errors} 个错误（保留 {days} 天）",

    // ===== osubot-core/src/storage.rs =====
    "storage.parse_next_update_failed" => "无法解析 next_update 时间戳，回退到当前时间",
    "storage.parse_pending_bind_created_failed" => "无法解析 pending_bind created_at，回退到当前时间",

    // ===== osubot-core/src/commands.rs =====

    // ===== osubot-core/src/highlight.rs =====
    "highlight.baseline_query_failed" => "批量基准快照查询失败，回退到逐用户查询",

    // ===== osubot-core/src/dedup.rs =====
    "dedup.creator_task_failed" => "去重创建者任务失败: {error}",

    // ===== osubot-core/src/rate_limiter.rs =====
    "rate_limiter.mutex_poisoned" => "rate limiter refill handle 互斥锁被污染，强制恢复",
    "rate_limiter.refill_panicked" => "rate limiter refill 任务 panic，正在重新生成",

    // ===== osubot-core/src/upstream.rs =====
    "upstream.provider_failed" => "上游 provider 查询失败，尝试下一个 provider",
    "upstream.dedup_error" => "上游去重错误: {error}",

    // ===== osubot-plugin/src/lib.rs =====
    "plugin.consecutive_error_reload" => "插件 {name} ({kind}) 连续错误，自动重载",
    "plugin.reload_failed" => "重载失败: {error}",
    "plugin.error" => "插件 {name} ({kind}) 错误: {error}",
    "plugin.panicked" => "插件 {name} ({kind}) panic: {error}",
    "plugin.consecutive_panic_reload" => "插件 {name} ({kind}) 连续 panic，自动重载",
    "plugin.timeout" => "插件 {name} ({kind}) 超时: {error}",
    "plugin.consecutive_timeout_reload" => "插件 {name} ({kind}) 连续超时，自动重载",
    "plugin.timeout_skip_reload" => "插件 {name} ({kind}) 超时，跳过重载等待阈值",
    "plugin.disabled" => "插件 {name} 已禁用，跳过",
    "plugin.module_loaded" => "插件 {name} 模块已加载",
    "plugin.instantiated" => "插件 {name} 实例已创建",
    "plugin.on_load_completed" => "插件 {name} on_load 已完成",
    "plugin.command_consecutive_error" => "插件 {name} 命令 连续错误，自动重载",
    "plugin.command_error" => "插件 {name} 命令 错误: {error}",
    "plugin.command_panicked" => "插件 {name} 命令 panic: {error}",
    "plugin.command_reload_after_panic_failed" => "panic 后重载失败: {error}",
    "plugin.command_timeout" => "插件 {name} 命令 超时",
    "plugin.command_consecutive_timeout" => "插件 {name} 命令 连续超时，自动重载",
    "plugin.on_message_consecutive_error" => "插件 {name} on_message 连续错误，自动重载",
    "plugin.on_message_error" => "插件 {name} on_message 错误: {error}",
    "plugin.on_message_panicked" => "插件 {name} on_message panic: {error}",
    "plugin.on_message_reload_failed" => "panic 后重载失败: {error}",
    "plugin.on_message_timeout" => "插件 {name} on_message 超时",
    "plugin.on_message_consecutive_timeout" => "插件 {name} on_message 连续超时，自动重载",
    "plugin.tick_registry_poisoned" => "tick_registry 互斥锁被污染，强制恢复（数据可能不一致）",
    "plugin.drop_without_shutdown" => "PluginManager 未走 shutdown() 直接 drop，跳过 on_unload（slots={slots}）",
    "plugin.on_tick_consecutive_error" => "插件 {name} on_tick 连续错误，自动重载",
    "plugin.on_tick_error" => "插件 {name} on_tick 错误: {error}",
    "plugin.on_tick_panicked" => "插件 {name} on_tick panic: {error}",
    "plugin.on_tick_consecutive_panic" => "插件 {name} on_tick 连续 panic，自动重载",
    "plugin.on_tick_timeout" => "插件 {name} on_tick 超时",
    "plugin.on_tick_consecutive_timeout" => "插件 {name} on_tick 连续超时，自动重载",
    "plugin.on_unload_consecutive_error" => "插件 {name} on_unload 连续错误，自动重载",
    "plugin.on_unload_error" => "插件 {name} on_unload 错误: {error}",
    "plugin.on_unload_panicked" => "插件 {name} on_unload panic: {error}",
    "plugin.on_unload_consecutive_panic" => "插件 {name} on_unload 连续 panic，自动重载",
    "plugin.on_unload_timeout" => "插件 {name} on_unload 超时，继续执行 {context}",
    "plugin.unloaded" => "插件 {name} 已卸载",
    "plugin.diff_complete" => "插件 diff 完成: 添加 {to_add}, 移除 {to_remove}, 重载 {to_reload}",
    "plugin.removed" => "插件 {name} 已移除",
    "plugin.invalid_path" => "路径无效，跳过: {error}",
    "plugin.compile_failed" => "WASM 编译失败，跳过: {error}",
    "plugin.instance_build_failed" => "实例构建失败，跳过: {error}",
    "plugin.on_load_failed" => "on_load 失败: {error}",
    "plugin.added" => "插件 {name} 已添加",
    "plugin.reload_invalid_path" => "路径无效，跳过重载: {error}",
    "plugin.reload_compile_failed" => "WASM 编译失败，跳过重载: {error}",
    "plugin.reload_instance_failed" => "实例构建失败，跳过重载: {error}",
    "plugin.reload_too_many_times" => "插件 {name} 重载失败 {consecutive} 次，需要手动重载",
    "plugin.reload_too_many_times_all" => "reload_all 中插件重载失败次数过多，需要手动重载",
    "plugin.reloaded" => "插件 {name} 已重载",
    "plugin.manager_compacted" => "PluginManager 已压缩: {old_len} → {new_len}（移除 {removed}）",

    // ===== osubot-plugin/src/instance.rs =====
    "instance.plugin_loaded" => "插件已加载",
    "instance.plugin_protocol_too_new" => "插件协议版本 {plugin_version} 高于宿主支持的 {host_version}",
    "instance.dealloc_length_prefix_failed" => "dealloc_result: 无法读取长度前缀，跳过释放（WASM 线性内存泄漏）",

    // ===== BridgeError Display（开发者可见） =====
    "bridge.err_json_parse" => "JSON 解析失败: {detail}",
    "bridge.err_missing_field" => "缺少字段 '{field}'",
    "bridge.err_invalid_mode" => "无效游戏模式: {mode}",
    "bridge.err_http_request" => "HTTP 请求失败: {detail}",
    "bridge.err_database" => "数据库查询失败: {detail}",
    "bridge.err_send_msg" => "宿主函数调用失败: {detail}",
    "bridge.err_unknown_host" => "未知宿主函数: {detail}",
    "bridge.err_validation" => "参数校验失败: {detail}",

    // ===== osubot-render/src/cache.rs =====
    "render.cache_dir_failed" => "无法创建缓存目录: {error}",
    "render.body_download_failed" => "body 下载失败，将重试",
    "render.server_error_retry" => "服务器错误，将重试",
    "render.client_error_abort" => "客户端错误，中止",
    "render.request_failed_retry" => "请求失败，将重试",
    "render.cache_write_failed" => "无法缓存 {url}: {error}",
    "render.svg_rasterize_failed" => "SVG 栅格化失败，回退到原始 SVG",
    "render.batch_fetch_failed" => "并行批量获取图片失败",
    "render.batch_join_error" => "并行图片获取 join 错误",
    "render.inline_utf8_invalid" => "图片内联产生无效 UTF-8: {error}",
    "render.cleanup_cutoff_failed" => "无法计算缓存清理的截止时间",
    "render.cleanup_read_dir_failed" => "无法读取缓存目录进行清理: {error}",
    "render.cleanup_delete_failed" => "无法删除缓存文件 {path}: {error}",
    "render.cleanup_summary" => "缓存清理完成：删除了 {deleted} 个文件，{errors} 个错误（保留 {days} 天）",

    // ===== osubot-render/src/lib.rs =====
    "render.download_avatar" => "正在下载头像: {url}",
    "render.avatar_download_failed" => "头像下载失败: {error}",
    "render.avatar_downloaded" => "头像已下载: {bytes} 字节",
    "render.profile_avatar_url_empty" => "profile 头像 URL 为空",
    "render.preprocess_cover" => "正在预处理封面图片...",
    "render.html_generated" => "HTML 已生成，开始渲染...",
    "render.score_card_timeout" => "成绩卡片渲染超时（60秒），阻塞任务已中止",
    "render.profile_card_timeout" => "个人资料卡片渲染超时（60秒），阻塞任务已中止",
    "render.score_list_timeout" => "成绩列表渲染超时（{secs}秒）",
    "render.err_jpeg_encode" => "JPEG 编码: {error}",
    "render.err_avatar_decode" => "头像解码: {error}",
    "render.err_avatar_fetch" => "头像: {error}",
    "render.err_hero_fetch" => "hero: {error}",
    "render.err_hero_decode" => "hero banner 解码",
    "render.err_render_timeout" => "渲染超时（60秒）",
    "render.err_score_list_timeout" => "成绩列表渲染超时（{secs}秒）",
    "render.err_size_mismatch" => "非平铺渲染尺寸不匹配: 期望 {expected}，实际 {actual}",
    "render.err_tile_size_mismatch" => "tile {tile} 尺寸不匹配: 期望 {expected}，实际 {actual}",

    // ===== osubot/src/main.rs (!mode) =====
    "main.set_default_mode" => "用户 {user_id} 设置默认模式为 {mode}",
    "main.set_default_mode_error" => "无法保存用户 {user_id} 的默认模式设置: {error}",
    "main.get_default_mode" => "用户 {user_id} 查询默认模式",
    "main.get_default_mode_error" => "无法获取用户 {user_id} 的默认模式: {error}",
    "main.find_qq_by_username_error" => "通过用户名 '{username}' 查找 QQ 时数据库错误: {error}",

    // ===== osubot-render/src/render.rs =====
    "render.resource_channel_disconnected" => "资源 channel 已断开，使用部分资源继续",
    "render.err_cancelled" => "渲染已取消",

    // ===== osubot/src/main.rs (!rv) =====
    "main.beatmap_preview_parse_failed" => "!rv 参数解析失败: {error}",
    "main.beatmap_preview_mods_parse_failed" => "!rv mod 解析失败: {error}",
    "main.beatmap_preview_mods_invalid" => "!rv mod 校验失败: {error}",
    "main.beatmap_preview_convert_unsupported" => "!rv 非 osu! 谱面不支持模式转换 (source_mode={source_mode}, target_mode={target_mode})",
    "main.beatmap_preview_convert_failed" => "!rv 谱面转换失败: {error}",
    "main.beatmap_preview_render_failed" => "!rv 预览渲染失败: {error}",
    "main.beatmap_preview_render_timeout" => "!rv 预览渲染超时",
    "main.beatmap_preview_read_failed" => "!rv 读取渲染结果失败: {error}",
    "main.beatmap_audio_send_failed" => "发送预览音频失败: {error}",
    "main.beatmap_preview_send_failed" => "发送预览图片失败: {error}",

    // ===== osubot/src/score_query/mod.rs =====
    "pipeline.unexpected_score_list_card_in_single_path" => "run_score_query_pipeline: 单成绩分支遇到 ScoreListCard，请检查 is_summary 配置",

    // ===== osubot/src/match_listener/ (ml 命令与后台轮询) =====
    "ml.command_received" => "!ml 命令: {action}",
    "ml.start_success_log" => "群 {group_id} 开始监听比赛 {match_id}",
    "ml.stop_success_log" => "群 {group_id} 停止监听比赛 {match_id}",
    "ml.stop_all_log" => "群 {group_id} 停止监听所有比赛（{count} 个）",
    "ml.list_log" => "群 {group_id} 查询监听列表（{count} 个）",
    "ml.status_log" => "群 {group_id} 查询比赛 {match_id} 状态",
    "ml.not_found_log" => "群 {group_id} 未找到比赛 {match_id}",
    "ml.already_listening_log" => "群 {group_id} 已在监听比赛 {match_id}，跳过",
    "ml.limit_exceeded_log" => "群 {group_id} 监听数量达上限（{limit}），拒绝新增比赛 {match_id}",
    "ml.fetch_match_failed_log" => "获取比赛 {match_id} 信息失败: {error}",
    "ml.poller_started" => "比赛监听轮询任务已启动",
    "ml.poller_stopped" => "比赛监听轮询任务已停止",
    "ml.poller_tick" => "比赛监听轮询心跳，活跃监听数: {count}",
    "ml.poller_match_fetch_failed" => "轮询: 获取比赛 {match_id} 失败: {error}",
    "ml.poller_new_game" => "轮询: 比赛 {match_id} 检测到新场次 {game_id}",
    "ml.poller_match_completed" => "轮询: 比赛 {match_id} 已结束",
    "ml.poller_notify_failed" => "轮询: 发送比赛 {match_id} 通知失败",
    "ml.poller_render_failed" => "轮询: 渲染比赛 {match_id} 结果卡片失败，回退到文本",
    "ml.notify_sent" => "已向群 {group_id} 发送比赛 {match_id} 的通知",
    "ml.notify_image_sent" => "已向群 {group_id} 发送比赛 {match_id} 的结果图片（{bytes} 字节）",
    "ml.notify_text_fallback" => "图片发送失败，回退到文本通知",
};

pub fn log_str(key: &str) -> &'static str {
    LOG_STRINGS.get(key).copied().unwrap_or_else(|| {
        tracing::warn!(key = key, "unknown log string key, returning placeholder");
        "???"
    })
}

pub fn user_str(key: &str) -> &'static str {
    USER_STRINGS.get(key).copied().unwrap_or_else(|| {
        tracing::warn!(key = key, "unknown user string key, returning placeholder");
        "???"
    })
}

#[macro_export]
macro_rules! log_fmt {
    ($key:expr) => {
        $crate::strings::LogFmt::new($crate::strings::log_str($key))
    };
    ($key:expr $(, $k:ident = $v:expr)*) => {{
        $crate::strings::LogFmt::new($crate::strings::log_str($key))
            $(.with_arg(stringify!($k), $v.to_string()))*
    }};
}
